baseURL = 'https://hovanja2011.github.io/'
title = 'The test hugo site'
theme = 'lightbi-hugo'

defaultContentLanguage = 'ru'
defaultContentLanguageInSubdir = true
[languages]
    [languages.en]
        languageName = 'English'
        weight = 2
        contentDir = 'content/en'
        title = 'Test hugo-site'
    [languages.ru]
        languageName = 'Russian'
        weight = 1
        contentDir = 'content/ru'
        title = 'Тестовый hugo-сайт'
  
[Author]
    name = "Ann Hovanskaya"

[[menu.main]]
    name = "Home"
    url = "/"
    weight = 1

[[menu.main]]
    name = "Notes"
    url = "/notes/"
    weight = 2

#[[menu.main]]
#    name = "Tags"
#    url = "/tags/blog/"
#    weight = 3

#[[menu.main]]
#    name = "Collections"
#    url = "/collections/"
#    weight = 4

[[menu.main]]
    name = "About"
    url = "/about/"
    weight = 5

